name: build
on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-20.04
    steps:
      -   name: checkout
          uses: actions/checkout@v4

      -   name: install advzip
          run: sudo apt-get install -y advancecomp

      -   name: setup java
          uses: actions/setup-java@v4
          with:
            distribution: zulu
            java-version: 21

      -   name: setup gradle
          uses: gradle/actions/setup-gradle@v3
          with:
            cache-read-only: false

      -   name: do the build
          run: ./gradlew assemble --stacktrace
          continue-on-error: true

      -   name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: omnilook-artifacts-v${{ github.run_number }}
            path: |
              build/libs/*
      -   name: upload dev artifacts
          uses: actions/upload-artifact@v4
          with:
            name: omnilook-dev-artifacts-v${{ github.run_number }}
            path: |
              build/devlibs/*