name: build
on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip]')"
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      -   name: checkout
          uses: actions/checkout@v4

      -   name: install advzip
          run: sudo apt-get install -y advancecomp

      -   name: gradle caches
          uses: useblacksmith/cache@v5
          with:
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper/

      -   name: setup java
          uses: useblacksmith/setup-java@v5
          with:
            distribution: zulu
            java-version: 21
            cache: gradle

      -   name: do the build
          run: ./gradlew assemble --stacktrace
          continue-on-error: true

      -   name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: omnilook-artifacts-v${{ github.run_number }}
            path: |
              build/libs/*
      -   name: upload dev artifacts
          uses: actions/upload-artifact@v4
          with:
            name: omnilook-dev-artifacts-v${{ github.run_number }}
            path: |
              build/devlibs/*